version: "3"

services:
  node:
    build: ./ 
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop
      - PORT=3001

  mongodb:
    image: mongo:5.0.7
    container_name: car_shop_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017